Vagrant.configure("2") do |config|

    config.vm.define "node1" do |node1|
        node1.vm.box = "centos/7"
    end

    config.vm.define "node2" do |node2|
        node2.vm.box = "centos/7"
    end

    config.vm.define "node3" do |node3|
        node3.vm.box = "centos/7"
    end

end
